name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v1

      - name: Build and run services
        run: docker compose up -d

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Run UV sync
        run: uv sync

      - name: Install package in editable mode
        run: uv pip install -e .

      - name: Run tests
        run: uv run pytest
